// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static Building.Web.Mvc.Controllers.AccountController Account = new Building.Web.Mvc.Controllers.T4MVC_AccountController();
    public static Building.Web.Mvc.Controllers.HomeController Home = new Building.Web.Mvc.Controllers.T4MVC_HomeController();
    public static Building.Web.Mvc.Controllers.ManageController Manage = new Building.Web.Mvc.Controllers.T4MVC_ManageController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string ai_0_15_0_build58334_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ai.0.15.0-build58334.min.js") ? Url("ai.0.15.0-build58334.min.js") : Url("ai.0.15.0-build58334.js");
        public static readonly string ai_0_15_0_build58334_min_js = Url("ai.0.15.0-build58334.min.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class AdminTheme {
            private const string URLPATH = "~/Content/AdminTheme";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _1_3_4_html = Url("1.3.4.html");
            public static readonly string _1_3_4_2_html = Url("1.3.4_2.html");
            public static readonly string blank_html = Url("blank.html");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class build {
                private const string URLPATH = "~/Content/AdminTheme/build";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class demo {
                    private const string URLPATH = "~/Content/AdminTheme/build/demo";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string email_confirmation_html = Url("email-confirmation.html");
                    public static readonly string email_contrast_html = Url("email-contrast.html");
                    public static readonly string email_navbar_html = Url("email-navbar.html");
                    public static readonly string email_newsletter_html = Url("email-newsletter.html");
                }
            
            }
        
            public static readonly string buttons_html = Url("buttons.html");
            public static readonly string calendar_html = Url("calendar.html");
            public static readonly string content_slider_html = Url("content-slider.html");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class dist {
                private const string URLPATH = "~/Content/AdminTheme/dist";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class avatars {
                    private const string URLPATH = "~/Content/AdminTheme/dist/avatars";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string avatar_png = Url("avatar.png");
                    public static readonly string avatar1_png = Url("avatar1.png");
                    public static readonly string avatar2_png = Url("avatar2.png");
                    public static readonly string avatar3_png = Url("avatar3.png");
                    public static readonly string avatar4_png = Url("avatar4.png");
                    public static readonly string avatar5_png = Url("avatar5.png");
                    public static readonly string profile_pic_jpg = Url("profile-pic.jpg");
                    public static readonly string user_jpg = Url("user.jpg");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class css {
                    private const string URLPATH = "~/Content/AdminTheme/dist/css";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ace_rtl_min_css = Url("ace-rtl.min.css");
                    public static readonly string ace_min_css = Url("ace.min.css");
                    public static readonly string bootstrap_datepicker3_min_css = Url("bootstrap-datepicker3.min.css");
                    public static readonly string bootstrap_datetimepicker_min_css = Url("bootstrap-datetimepicker.min.css");
                    public static readonly string bootstrap_duallistbox_min_css = Url("bootstrap-duallistbox.min.css");
                    public static readonly string bootstrap_editable_min_css = Url("bootstrap-editable.min.css");
                    public static readonly string bootstrap_multiselect_min_css = Url("bootstrap-multiselect.min.css");
                    public static readonly string bootstrap_timepicker_min_css = Url("bootstrap-timepicker.min.css");
                    public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
                    public static readonly string chosen_min_css = Url("chosen.min.css");
                    public static readonly string colorbox_min_css = Url("colorbox.min.css");
                    public static readonly string colorpicker_min_css = Url("colorpicker.min.css");
                    public static readonly string daterangepicker_min_css = Url("daterangepicker.min.css");
                    public static readonly string dropzone_min_css = Url("dropzone.min.css");
                    public static readonly string fullcalendar_min_css = Url("fullcalendar.min.css");
                    public static readonly string jquery_ui_custom_min_css = Url("jquery-ui.custom.min.css");
                    public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                    public static readonly string jquery_gritter_min_css = Url("jquery.gritter.min.css");
                    public static readonly string prettify_min_css = Url("prettify.min.css");
                    public static readonly string select2_min_css = Url("select2.min.css");
                    public static readonly string ui_jqgrid_min_css = Url("ui.jqgrid.min.css");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/AdminTheme/dist/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string email1_png = Url("email1.png");
                    public static readonly string email2_png = Url("email2.png");
                    public static readonly string email3_png = Url("email3.png");
                    public static readonly string email4_png = Url("email4.png");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class gallery {
                        private const string URLPATH = "~/Content/AdminTheme/dist/images/gallery";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string image_1_jpg = Url("image-1.jpg");
                        public static readonly string image_2_jpg = Url("image-2.jpg");
                        public static readonly string image_3_jpg = Url("image-3.jpg");
                        public static readonly string image_4_jpg = Url("image-4.jpg");
                        public static readonly string image_5_jpg = Url("image-5.jpg");
                        public static readonly string image_6_jpg = Url("image-6.jpg");
                        public static readonly string thumb_1_jpg = Url("thumb-1.jpg");
                        public static readonly string thumb_2_jpg = Url("thumb-2.jpg");
                        public static readonly string thumb_3_jpg = Url("thumb-3.jpg");
                        public static readonly string thumb_4_jpg = Url("thumb-4.jpg");
                        public static readonly string thumb_5_jpg = Url("thumb-5.jpg");
                        public static readonly string thumb_6_jpg = Url("thumb-6.jpg");
                    }
                
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class js {
                    private const string URLPATH = "~/Content/AdminTheme/dist/js";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ace_elements_min_js = Url("ace-elements.min.js");
                    public static readonly string ace_extra_min_js = Url("ace-extra.min.js");
                    public static readonly string ace_min_js = Url("ace.min.js");
                    public static readonly string additional_methods_min_js = Url("additional-methods.min.js");
                    public static readonly string autosize_min_js = Url("autosize.min.js");
                    public static readonly string bootbox_min_js = Url("bootbox.min.js");
                    public static readonly string bootstrap_colorpicker_min_js = Url("bootstrap-colorpicker.min.js");
                    public static readonly string bootstrap_multiselect_min_js = Url("bootstrap-multiselect.min.js");
                    public static readonly string bootstrap_tag_min_js = Url("bootstrap-tag.min.js");
                    public static readonly string bootstrap_wysiwyg_min_js = Url("bootstrap-wysiwyg.min.js");
                    public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
                    public static readonly string chosen_jquery_min_js = Url("chosen.jquery.min.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class dataTables {
                        private const string URLPATH = "~/Content/AdminTheme/dist/js/dataTables";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                        public static class extensions {
                            private const string URLPATH = "~/Content/AdminTheme/dist/js/dataTables/extensions";
                            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                            public static class buttons {
                                private const string URLPATH = "~/Content/AdminTheme/dist/js/dataTables/extensions/buttons";
                                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                                public static readonly string buttons_colVis_min_js = Url("buttons.colVis.min.js");
                                public static readonly string buttons_flash_min_js = Url("buttons.flash.min.js");
                                public static readonly string buttons_html5_min_js = Url("buttons.html5.min.js");
                                public static readonly string buttons_print_min_js = Url("buttons.print.min.js");
                                public static readonly string dataTables_buttons_min_js = Url("dataTables.buttons.min.js");
                                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                                public static class swf {
                                    private const string URLPATH = "~/Content/AdminTheme/dist/js/dataTables/extensions/buttons/swf";
                                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                                    public static readonly string flashExport_swf = Url("flashExport.swf");
                                }
                            
                            }
                        
                            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                            public static class select {
                                private const string URLPATH = "~/Content/AdminTheme/dist/js/dataTables/extensions/select";
                                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                                public static readonly string dataTables_select_min_js = Url("dataTables.select.min.js");
                            }
                        
                        }
                    
                        public static readonly string jquery_dataTables_bootstrap_min_js = Url("jquery.dataTables.bootstrap.min.js");
                        public static readonly string jquery_dataTables_min_js = Url("jquery.dataTables.min.js");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class date_time {
                        private const string URLPATH = "~/Content/AdminTheme/dist/js/date-time";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string bootstrap_datepicker_min_js = Url("bootstrap-datepicker.min.js");
                        public static readonly string bootstrap_datetimepicker_min_js = Url("bootstrap-datetimepicker.min.js");
                        public static readonly string bootstrap_timepicker_min_js = Url("bootstrap-timepicker.min.js");
                        public static readonly string daterangepicker_min_js = Url("daterangepicker.min.js");
                        public static readonly string moment_min_js = Url("moment.min.js");
                    }
                
                    public static readonly string dropzone_min_js = Url("dropzone.min.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class flot {
                        private const string URLPATH = "~/Content/AdminTheme/dist/js/flot";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string jquery_flot_min_js = Url("jquery.flot.min.js");
                        public static readonly string jquery_flot_pie_min_js = Url("jquery.flot.pie.min.js");
                        public static readonly string jquery_flot_resize_min_js = Url("jquery.flot.resize.min.js");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class fuelux {
                        private const string URLPATH = "~/Content/AdminTheme/dist/js/fuelux";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string fuelux_spinner_min_js = Url("fuelux.spinner.min.js");
                        public static readonly string fuelux_tree_min_js = Url("fuelux.tree.min.js");
                        public static readonly string fuelux_wizard_min_js = Url("fuelux.wizard.min.js");
                    }
                
                    public static readonly string fullcalendar_min_js = Url("fullcalendar.min.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class jqGrid {
                        private const string URLPATH = "~/Content/AdminTheme/dist/js/jqGrid";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                        public static class i18n {
                            private const string URLPATH = "~/Content/AdminTheme/dist/js/jqGrid/i18n";
                            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                            public static readonly string grid_locale_en_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/grid.locale-en.min.js") ? Url("grid.locale-en.min.js") : Url("grid.locale-en.js");
                        }
                    
                        public static readonly string jquery_jqGrid_min_js = Url("jquery.jqGrid.min.js");
                    }
                
                    public static readonly string jquery_ui_custom_min_js = Url("jquery-ui.custom.min.js");
                    public static readonly string jquery_ui_min_js = Url("jquery-ui.min.js");
                    public static readonly string jquery_bootstrap_duallistbox_min_js = Url("jquery.bootstrap-duallistbox.min.js");
                    public static readonly string jquery_colorbox_min_js = Url("jquery.colorbox.min.js");
                    public static readonly string jquery_easypiechart_min_js = Url("jquery.easypiechart.min.js");
                    public static readonly string jquery_gritter_min_js = Url("jquery.gritter.min.js");
                    public static readonly string jquery_hotkeys_min_js = Url("jquery.hotkeys.min.js");
                    public static readonly string jquery_inputlimiter_1_3_1_min_js = Url("jquery.inputlimiter.1.3.1.min.js");
                    public static readonly string jquery_knob_min_js = Url("jquery.knob.min.js");
                    public static readonly string jquery_maskedinput_min_js = Url("jquery.maskedinput.min.js");
                    public static readonly string jquery_min_js = Url("jquery.min.js");
                    public static readonly string jquery_mobile_custom_min_js = Url("jquery.mobile.custom.min.js");
                    public static readonly string jquery_nestable_min_js = Url("jquery.nestable.min.js");
                    public static readonly string jquery_raty_min_js = Url("jquery.raty.min.js");
                    public static readonly string jquery_sparkline_min_js = Url("jquery.sparkline.min.js");
                    public static readonly string jquery_ui_touch_punch_min_js = Url("jquery.ui.touch-punch.min.js");
                    public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class markdown {
                        private const string URLPATH = "~/Content/AdminTheme/dist/js/markdown";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string bootstrap_markdown_min_js = Url("bootstrap-markdown.min.js");
                        public static readonly string markdown_min_js = Url("markdown.min.js");
                    }
                
                    public static readonly string prettify_min_js = Url("prettify.min.js");
                    public static readonly string select2_min_js = Url("select2.min.js");
                    public static readonly string spin_min_js = Url("spin.min.js");
                    public static readonly string typeahead_jquery_min_js = Url("typeahead.jquery.min.js");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class x_editable {
                        private const string URLPATH = "~/Content/AdminTheme/dist/js/x-editable";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ace_editable_min_js = Url("ace-editable.min.js");
                        public static readonly string bootstrap_editable_min_js = Url("bootstrap-editable.min.js");
                    }
                
                }
            
            }
        
            public static readonly string dropzone_html = Url("dropzone.html");
            public static readonly string dummy_html = Url("dummy.html");
            public static readonly string elements_html = Url("elements.html");
            public static readonly string email_html = Url("email.html");
            public static readonly string error_404_html = Url("error-404.html");
            public static readonly string error_500_html = Url("error-500.html");
            public static readonly string faq_html = Url("faq.html");
            public static readonly string form_elements_2_html = Url("form-elements-2.html");
            public static readonly string form_elements_html = Url("form-elements.html");
            public static readonly string form_wizard_html = Url("form-wizard.html");
            public static readonly string gallery_html = Url("gallery.html");
            public static readonly string grid_html = Url("grid.html");
            public static readonly string inbox_html = Url("inbox.html");
            public static readonly string index_html = Url("index.html");
            public static readonly string invoice_html = Url("invoice.html");
            public static readonly string jqgrid_html = Url("jqgrid.html");
            public static readonly string jquery_ui_html = Url("jquery-ui.html");
            public static readonly string login_html = Url("login.html");
            public static readonly string mobile_menu_1_html = Url("mobile-menu-1.html");
            public static readonly string mobile_menu_2_html = Url("mobile-menu-2.html");
            public static readonly string mobile_menu_3_html = Url("mobile-menu-3.html");
            public static readonly string nestable_list_html = Url("nestable-list.html");
            public static readonly string pricing_html = Url("pricing.html");
            public static readonly string profile_html = Url("profile.html");
            public static readonly string tables_html = Url("tables.html");
            public static readonly string timeline_html = Url("timeline.html");
            public static readonly string top_menu_html = Url("top-menu.html");
            public static readonly string treeview_html = Url("treeview.html");
            public static readonly string two_menu_1_html = Url("two-menu-1.html");
            public static readonly string two_menu_2_html = Url("two-menu-2.html");
            public static readonly string typography_html = Url("typography.html");
            public static readonly string widgets_html = Url("widgets.html");
            public static readonly string wysiwyg_html = Url("wysiwyg.html");
        }
    
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string ai_0_15_0_build58334_js = "~/Scripts/ai.0.15.0-build58334.js"; 
                public const string ai_0_15_0_build58334_min_js = "~/Scripts/ai.0.15.0-build58334.min.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_1_10_2_intellisense_js = "~/Scripts/jquery-1.10.2.intellisense.js"; 
                public const string jquery_1_10_2_js = "~/Scripts/jquery-1.10.2.js"; 
                public const string jquery_1_10_2_min_js = "~/Scripts/jquery-1.10.2.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class AdminTheme 
            {
                public static partial class build 
                {
                    public static partial class demo 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static partial class dist 
                {
                    public static partial class avatars 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class css 
                    {
                        public static class Assets
                        {
                            public const string ace_rtl_min_css = "~/Content/AdminTheme/dist/css/ace-rtl.min.css";
                            public const string ace_min_css = "~/Content/AdminTheme/dist/css/ace.min.css";
                            public const string bootstrap_datepicker3_min_css = "~/Content/AdminTheme/dist/css/bootstrap-datepicker3.min.css";
                            public const string bootstrap_datetimepicker_min_css = "~/Content/AdminTheme/dist/css/bootstrap-datetimepicker.min.css";
                            public const string bootstrap_duallistbox_min_css = "~/Content/AdminTheme/dist/css/bootstrap-duallistbox.min.css";
                            public const string bootstrap_editable_min_css = "~/Content/AdminTheme/dist/css/bootstrap-editable.min.css";
                            public const string bootstrap_multiselect_min_css = "~/Content/AdminTheme/dist/css/bootstrap-multiselect.min.css";
                            public const string bootstrap_timepicker_min_css = "~/Content/AdminTheme/dist/css/bootstrap-timepicker.min.css";
                            public const string bootstrap_min_css = "~/Content/AdminTheme/dist/css/bootstrap.min.css";
                            public const string chosen_min_css = "~/Content/AdminTheme/dist/css/chosen.min.css";
                            public const string colorbox_min_css = "~/Content/AdminTheme/dist/css/colorbox.min.css";
                            public const string colorpicker_min_css = "~/Content/AdminTheme/dist/css/colorpicker.min.css";
                            public const string daterangepicker_min_css = "~/Content/AdminTheme/dist/css/daterangepicker.min.css";
                            public const string dropzone_min_css = "~/Content/AdminTheme/dist/css/dropzone.min.css";
                            public const string fullcalendar_min_css = "~/Content/AdminTheme/dist/css/fullcalendar.min.css";
                            public const string jquery_ui_custom_min_css = "~/Content/AdminTheme/dist/css/jquery-ui.custom.min.css";
                            public const string jquery_ui_min_css = "~/Content/AdminTheme/dist/css/jquery-ui.min.css";
                            public const string jquery_gritter_min_css = "~/Content/AdminTheme/dist/css/jquery.gritter.min.css";
                            public const string prettify_min_css = "~/Content/AdminTheme/dist/css/prettify.min.css";
                            public const string select2_min_css = "~/Content/AdminTheme/dist/css/select2.min.css";
                            public const string ui_jqgrid_min_css = "~/Content/AdminTheme/dist/css/ui.jqgrid.min.css";
                        }
                    }
                    public static partial class images 
                    {
                        public static partial class gallery 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                        }
                    }
                    public static partial class js 
                    {
                        public static partial class dataTables 
                        {
                            public static partial class extensions 
                            {
                                public static partial class buttons 
                                {
                                    public static partial class swf 
                                    {
                                        public static class Assets
                                        {
                                        }
                                    }
                                    public static class Assets
                                    {
                                        public const string buttons_colVis_min_js = "~/Content/AdminTheme/dist/js/dataTables/extensions/buttons/buttons.colVis.min.js"; 
                                        public const string buttons_flash_min_js = "~/Content/AdminTheme/dist/js/dataTables/extensions/buttons/buttons.flash.min.js"; 
                                        public const string buttons_html5_min_js = "~/Content/AdminTheme/dist/js/dataTables/extensions/buttons/buttons.html5.min.js"; 
                                        public const string buttons_print_min_js = "~/Content/AdminTheme/dist/js/dataTables/extensions/buttons/buttons.print.min.js"; 
                                        public const string dataTables_buttons_min_js = "~/Content/AdminTheme/dist/js/dataTables/extensions/buttons/dataTables.buttons.min.js"; 
                                    }
                                }
                                public static partial class select 
                                {
                                    public static class Assets
                                    {
                                        public const string dataTables_select_min_js = "~/Content/AdminTheme/dist/js/dataTables/extensions/select/dataTables.select.min.js"; 
                                    }
                                }
                                public static class Assets
                                {
                                }
                            }
                            public static class Assets
                            {
                                public const string jquery_dataTables_bootstrap_min_js = "~/Content/AdminTheme/dist/js/dataTables/jquery.dataTables.bootstrap.min.js"; 
                                public const string jquery_dataTables_min_js = "~/Content/AdminTheme/dist/js/dataTables/jquery.dataTables.min.js"; 
                            }
                        }
                        public static partial class date_time 
                        {
                            public static class Assets
                            {
                                public const string bootstrap_datepicker_min_js = "~/Content/AdminTheme/dist/js/date-time/bootstrap-datepicker.min.js"; 
                                public const string bootstrap_datetimepicker_min_js = "~/Content/AdminTheme/dist/js/date-time/bootstrap-datetimepicker.min.js"; 
                                public const string bootstrap_timepicker_min_js = "~/Content/AdminTheme/dist/js/date-time/bootstrap-timepicker.min.js"; 
                                public const string daterangepicker_min_js = "~/Content/AdminTheme/dist/js/date-time/daterangepicker.min.js"; 
                                public const string moment_min_js = "~/Content/AdminTheme/dist/js/date-time/moment.min.js"; 
                            }
                        }
                        public static partial class flot 
                        {
                            public static class Assets
                            {
                                public const string jquery_flot_min_js = "~/Content/AdminTheme/dist/js/flot/jquery.flot.min.js"; 
                                public const string jquery_flot_pie_min_js = "~/Content/AdminTheme/dist/js/flot/jquery.flot.pie.min.js"; 
                                public const string jquery_flot_resize_min_js = "~/Content/AdminTheme/dist/js/flot/jquery.flot.resize.min.js"; 
                            }
                        }
                        public static partial class fuelux 
                        {
                            public static class Assets
                            {
                                public const string fuelux_spinner_min_js = "~/Content/AdminTheme/dist/js/fuelux/fuelux.spinner.min.js"; 
                                public const string fuelux_tree_min_js = "~/Content/AdminTheme/dist/js/fuelux/fuelux.tree.min.js"; 
                                public const string fuelux_wizard_min_js = "~/Content/AdminTheme/dist/js/fuelux/fuelux.wizard.min.js"; 
                            }
                        }
                        public static partial class jqGrid 
                        {
                            public static partial class i18n 
                            {
                                public static class Assets
                                {
                                    public const string grid_locale_en_js = "~/Content/AdminTheme/dist/js/jqGrid/i18n/grid.locale-en.js"; 
                                }
                            }
                            public static class Assets
                            {
                                public const string jquery_jqGrid_min_js = "~/Content/AdminTheme/dist/js/jqGrid/jquery.jqGrid.min.js"; 
                            }
                        }
                        public static partial class markdown 
                        {
                            public static class Assets
                            {
                                public const string bootstrap_markdown_min_js = "~/Content/AdminTheme/dist/js/markdown/bootstrap-markdown.min.js"; 
                                public const string markdown_min_js = "~/Content/AdminTheme/dist/js/markdown/markdown.min.js"; 
                            }
                        }
                        public static partial class x_editable 
                        {
                            public static class Assets
                            {
                                public const string ace_editable_min_js = "~/Content/AdminTheme/dist/js/x-editable/ace-editable.min.js"; 
                                public const string bootstrap_editable_min_js = "~/Content/AdminTheme/dist/js/x-editable/bootstrap-editable.min.js"; 
                            }
                        }
                        public static class Assets
                        {
                            public const string ace_elements_min_js = "~/Content/AdminTheme/dist/js/ace-elements.min.js"; 
                            public const string ace_extra_min_js = "~/Content/AdminTheme/dist/js/ace-extra.min.js"; 
                            public const string ace_min_js = "~/Content/AdminTheme/dist/js/ace.min.js"; 
                            public const string additional_methods_min_js = "~/Content/AdminTheme/dist/js/additional-methods.min.js"; 
                            public const string autosize_min_js = "~/Content/AdminTheme/dist/js/autosize.min.js"; 
                            public const string bootbox_min_js = "~/Content/AdminTheme/dist/js/bootbox.min.js"; 
                            public const string bootstrap_colorpicker_min_js = "~/Content/AdminTheme/dist/js/bootstrap-colorpicker.min.js"; 
                            public const string bootstrap_multiselect_min_js = "~/Content/AdminTheme/dist/js/bootstrap-multiselect.min.js"; 
                            public const string bootstrap_tag_min_js = "~/Content/AdminTheme/dist/js/bootstrap-tag.min.js"; 
                            public const string bootstrap_wysiwyg_min_js = "~/Content/AdminTheme/dist/js/bootstrap-wysiwyg.min.js"; 
                            public const string bootstrap_min_js = "~/Content/AdminTheme/dist/js/bootstrap.min.js"; 
                            public const string chosen_jquery_min_js = "~/Content/AdminTheme/dist/js/chosen.jquery.min.js"; 
                            public const string dropzone_min_js = "~/Content/AdminTheme/dist/js/dropzone.min.js"; 
                            public const string fullcalendar_min_js = "~/Content/AdminTheme/dist/js/fullcalendar.min.js"; 
                            public const string jquery_ui_custom_min_js = "~/Content/AdminTheme/dist/js/jquery-ui.custom.min.js"; 
                            public const string jquery_ui_min_js = "~/Content/AdminTheme/dist/js/jquery-ui.min.js"; 
                            public const string jquery_bootstrap_duallistbox_min_js = "~/Content/AdminTheme/dist/js/jquery.bootstrap-duallistbox.min.js"; 
                            public const string jquery_colorbox_min_js = "~/Content/AdminTheme/dist/js/jquery.colorbox.min.js"; 
                            public const string jquery_easypiechart_min_js = "~/Content/AdminTheme/dist/js/jquery.easypiechart.min.js"; 
                            public const string jquery_gritter_min_js = "~/Content/AdminTheme/dist/js/jquery.gritter.min.js"; 
                            public const string jquery_hotkeys_min_js = "~/Content/AdminTheme/dist/js/jquery.hotkeys.min.js"; 
                            public const string jquery_inputlimiter_1_3_1_min_js = "~/Content/AdminTheme/dist/js/jquery.inputlimiter.1.3.1.min.js"; 
                            public const string jquery_knob_min_js = "~/Content/AdminTheme/dist/js/jquery.knob.min.js"; 
                            public const string jquery_maskedinput_min_js = "~/Content/AdminTheme/dist/js/jquery.maskedinput.min.js"; 
                            public const string jquery_min_js = "~/Content/AdminTheme/dist/js/jquery.min.js"; 
                            public const string jquery_mobile_custom_min_js = "~/Content/AdminTheme/dist/js/jquery.mobile.custom.min.js"; 
                            public const string jquery_nestable_min_js = "~/Content/AdminTheme/dist/js/jquery.nestable.min.js"; 
                            public const string jquery_raty_min_js = "~/Content/AdminTheme/dist/js/jquery.raty.min.js"; 
                            public const string jquery_sparkline_min_js = "~/Content/AdminTheme/dist/js/jquery.sparkline.min.js"; 
                            public const string jquery_ui_touch_punch_min_js = "~/Content/AdminTheme/dist/js/jquery.ui.touch-punch.min.js"; 
                            public const string jquery_validate_min_js = "~/Content/AdminTheme/dist/js/jquery.validate.min.js"; 
                            public const string prettify_min_js = "~/Content/AdminTheme/dist/js/prettify.min.js"; 
                            public const string select2_min_js = "~/Content/AdminTheme/dist/js/select2.min.js"; 
                            public const string spin_min_js = "~/Content/AdminTheme/dist/js/spin.min.js"; 
                            public const string typeahead_jquery_min_js = "~/Content/AdminTheme/dist/js/typeahead.jquery.min.js"; 
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string Site_css = "~/Content/Site.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


